
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Apr 24 15:56:53 EDT 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 34;
  public static final int DIVIDE = 36;
  public static final int INHERITS = 9;
  public static final int STR = 42;
  public static final int EQUALS = 35;
  public static final int POOL = 13;
  public static final int CASE = 2;
  public static final int LPAREN = 26;
  public static final int SEMI = 30;
  public static final int INT = 43;
  public static final int MINUS = 39;
  public static final int TILDE = 31;
  public static final int RPAREN = 27;
  public static final int NOT = 15;
  public static final int LT = 32;
  public static final int TYPE = 40;
  public static final int IN = 8;
  public static final int COMMA = 23;
  public static final int CLASS = 4;
  public static final int FI = 6;
  public static final int PLUS = 38;
  public static final int LOOP = 12;
  public static final int IF = 7;
  public static final int DOT = 24;
  public static final int LE = 33;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int TRUE = 19;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int ISVOID = 10;
  public static final int TIMES = 37;
  public static final int COLON = 22;
  public static final int LBRACE = 28;
  public static final int ELSE = 5;
  public static final int WHILE = 18;
  public static final int ESAC = 3;
  public static final int LET = 11;
  public static final int THEN = 17;
  public static final int RBRACE = 29;
  public static final int AT = 25;
  public static final int LARROW = 21;
  public static final int FALSE = 20;
  public static final int IDENTIFIER = 41;
}

